name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Add ENV to file
              run: | 
                echo ${{ vars.DEV_VAR }} >> env.txt
                ls -ltra
                cat env.txt
            